name: Deploy Microservices

on:
  push:
    branches:
      - main
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy repository to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ needs.provision.outputs.instance_public_ip }}
          username: ${{ needs.provision.outputs.instance_public_ip }}
          key: ${{ needs.provision.outputs.server_ssh_key }}
          source: "."
          target: "~/ecommerce"

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ needs.provision.outputs.instance_public_ip }}
          username: ${{ needs.provision.outputs.instance_public_ip }}
          key: ${{ needs.provision.outputs.server_ssh_key }}
          script: |
            cd ~/ecommerce

            echo "Stopping running containers..."
            docker compose down

            echo "Starting containers..."
            docker compose up -d --build
